package app

import "github.com/charmbracelet/x/ansi"

func displayClusterName(contextName, cluster string) string {
	if cluster != "" {
		return cluster
	}
	// Contexts generated by lift contain subscription/RG components that cannot
	// be safely split on hyphens. Resolve the display name from saved metadata.
	if locations, err := loadAgentLocations(); err == nil {
		for _, location := range locations {
			if location.Context == contextName && location.Cluster != "" {
				return location.Cluster
			}
		}
	}
	return contextName
}

func agentConnectionHeader(agent, location, status string, width int) string {
	if width <= 0 {
		width = 80
	}
	return ansi.Truncate("KMX / "+tuiField("agent", agent)+" · "+tuiField("location", location), width, "…") + "\n" +
		ansi.Truncate(tuiField("status", " "+status), width, "…")
}
